name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [linux]
    name: mises-sns ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Compile
        run: |
          CGO_ENABLED=0 go build -o outupt/mises cmd/main.go
      - name: Config
        run: |
          cp -rf .aws/* outupt/
          cp .env outupt/
      - name: 'Tar files'
        run: |
          cd outupt
          tar -czvf mises-sns.tar.gz mises .env appspec.yml scripts/
      - uses: actions/upload-artifact@v2
        with:
          name: mises-sns ${{ matrix.targetos }} ${{ matrix.arch }}
          path: outupt/mises-sns.tar.gz
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: mises-sns linux amd64
          path: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: |
          aws s3 cp \
           --recursive \
           --region us-east-2 \
           ./build s3://misesid
      - name: CodeDeploy to EC2
        run: |
          aws deploy create-deployment \
           --application-name mises-sns \
           --deployment-group-name MisesSnsDeployGroup \
           --s3-location bucket=misesid,key=mises-sns.tar.gz,bundleType=tgz \
           --file-exists-behavior OVERWRITE